/***** SETTINGS ACTIONS ******/
export const CHANGE_THEME = 'CHANGE_THEME';
export const CHANGE_UNITS = 'CHANGE_UNITS';

/***** SEARCH FETCHING ******/
export const SET_SEARCH_SUGGESTIONS = 'SET_SEARCH_SUGGESTIONS';
export const SET_CURRENT_SEARCH = 'SET_CURRENT_SEARCH';

/***** WEATHER ACTIONS ******/
export const SET_CURRENT_LOCATION = 'SET_CURRENT_LOCATION';
export const SET_CURRENT_WEATHER = 'SET_CURRENT_WEATHER';
export const SET_LOCATION_FORECAST = 'SET_LOCATION_FORECAST';

/***** FAVORITES ACTIONS ******/
export const SET_FAVORITES = 'SET_FAVORITES';
export const ADD_TO_FAVROITES = 'ADD_TO_FAVROITES';
export const REMOVE_FROM_FAVROITES = 'REMOVE_FROM_FAVROITES';