/***** APP SETTINGS ******/
export const CHANGE_THEME = 'CHANGE_THEME';
export const CHANGE_UNITS = 'CHANGE_UNITS';

/***** DATA FETCHING ******/
export const SEARCH_AUTOCOMPLETE = 'SEARCH_AUTOCOMPLETE';
export const FETCH_CURRENT_WEATHER = 'FETCH_CURRENT_WEATHER';
export const FETCH_FORECAST_5D = 'FETCH_FORECAST_5D';
